### PR TITLE
Upgrade API version to 51

### PR DESCRIPTION
**Pull request by wimvelzeboer**
Some elements of the Health Cloud require all apex classes used by customizations to be upgraded.

---
This change is [Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-mocks/112)

### CODE REVIEW

**Review by daveespo — APPROVED** [review]
> Reviewed 41 of 41 files at r1.
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-mocks/112)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by daveespo** [comment]
@wimvelzeboer  -- can you make sure you're basing this branch from the lastest master? I'm seeing a merge conflict on `sfdx-project.json`

**Comment by wimvelzeboer** [comment]
Hi @daveespo, sorry about that. Just rebased my branch again. Should be fine now. :-)

**Comment by ImJohnMDaniel** [comment]
@daveespo -- the verification build on this PR is failing.  The error says something about trying to delete the DevHub.  Can you investigate please?

**Comment by ImJohnMDaniel** [comment]
@wimvelzeboer Thanks for this.  Literally, @daveespo, @stohn777, and I were talking about updating the API on all the projects yesterday.

In general, the changes look fine.  I will setup a manual test today for these changes against the other AEP projects to verify there are no issues.

**Comment by daveespo** [comment]
Hi @wimvelzeboer  -- looks like when you rebased this morning, you introduced a syntax error into `project-scratch-def.json` (extra curly brace) -- can you patch that?

**Review by ImJohnMDaniel — APPROVED** [review]

**Comment by wimvelzeboer** [comment]
@daveespo Indeed, thats right. I just fixed it. Working a new computer and not everything is working as expected yet. :-(

**Review by daveespo — APPROVED** [review]

**Pull request merged**
