### PR TITLE
Feature/better verification messages

### PR DESCRIPTION
**Pull request by dfruddffdc**
Adds better logging around expected and actual values to help diagnose match failures, and better descriptions of matchers.
Addresses #58 and others.

Ported from FF internal repo.
Tests all passing in my org.

### CODE REVIEW

**Review by daveespo — APPROVED** [review]
I'm generally in favor of this PR -- however, I have a minor amount of concern about changing the format of the verification messages

Are there any circumstances where a user of the fflib-apex-mocks would be string matching on the Exception raised by `verify()` ?

**Comment by dfruddffdc** [comment]
> Are there any circumstances where a user of the fflib-apex-mocks would be string matching on the Exception raised by `verify()` ?

It's an interesting point!

Technically, yes, but the exceptions thrown by verify are not really intended to be caught (except for unit tests for the framework itself). When you have matchers and fuzzy expected call counts, I can't think of a compelling reason not to just let the thrown exception cause a test failure.

**Review by ImJohnMDaniel — APPROVED** [review]

**Comment by daveespo** [comment]
@dfruddffdc  -- excellent contribution!

**Comment by cropredyHelix** [comment]
@dfruddffdc - I am so happy with this enhancement

**Pull request merged**
